#pragma once

#include "resource.h"

#define MOD MOD_ALT

#define APPBAR_WINDOW_CLASS "MYWINBAR_TrayWnd"
#define EXPLORER_APPBAR_WINDOW_CLASS "Shell_TrayWnd"

#define MAX_WORKSPACE 10
#define MAX_WINDOW_PER_WORKSPACE 20

#define HOTKEY_DESTROY_WINDOW 1001

#define HOTKEY_MINIMIZE_WINDOW 1002
#define HOTKEY_MAXIMIZE_WINDOW 1003
#define HOTKEY_MAXIMIZE_ALL_WINDOW 1004
#define HOTKEY_MINIMIZE_ALL_WINDOW 1005

#define HOTKEY_SWITHTO_NEXT_WINDOW 1006
#define HOTKEY_SWITHTO_PREVIOUS_WINDOW 1007

#define HOTKEY_TILE_VERTICAL 1008
#define HOTKEY_TILE_HORIZONTAL 1009
#define HOTKEY_REFRESH_TILE 1010

#define HOTKEY_OPEN_TERMINAL 1011

#define HOTKEY_SWAPWINDOW_NEXT 1012
#define HOTKEY_SWAPWINDOW_PREVIOUS 1013

#define HOTKEY_SWITHTO_WORKSPACE_1 2001
#define HOTKEY_SWITHTO_WORKSPACE_2 2002
#define HOTKEY_SWITHTO_WORKSPACE_3 2003
#define HOTKEY_SWITHTO_WORKSPACE_4 2004
#define HOTKEY_SWITHTO_WORKSPACE_5 2005
#define HOTKEY_SWITHTO_WORKSPACE_6 2006
#define HOTKEY_SWITHTO_WORKSPACE_7 2007
#define HOTKEY_SWITHTO_WORKSPACE_8 2008
#define HOTKEY_SWITHTO_WORKSPACE_9 2009
#define HOTKEY_SWITHTO_WORKSPACE_10 2010

#define HOTKEY_SWITHTO_NEXT_WORKSPACE 2011
#define HOTKEY_SWITHTO_PREVIOUS_WORKSPACE 2012

#define HOTKEY_MOVEWINDOW_TO_WORKSPACE_1 5001
#define HOTKEY_MOVEWINDOW_TO_WORKSPACE_2 5002
#define HOTKEY_MOVEWINDOW_TO_WORKSPACE_3 5003
#define HOTKEY_MOVEWINDOW_TO_WORKSPACE_4 5004
#define HOTKEY_MOVEWINDOW_TO_WORKSPACE_5 5005
#define HOTKEY_MOVEWINDOW_TO_WORKSPACE_6 5006
#define HOTKEY_MOVEWINDOW_TO_WORKSPACE_7 5007
#define HOTKEY_MOVEWINDOW_TO_WORKSPACE_8 5008
#define HOTKEY_MOVEWINDOW_TO_WORKSPACE_9 5009
#define HOTKEY_MOVEWINDOW_TO_WORKSPACE_10 5010

#define HOTKEY_TOGGLE_EXPLORER_TASKBAR 8001
#define HOTKEY_QUIT_APP 8002

#define OVERLAP_WINDOW_MODE 0x02

#define SWAPWINDOW_NEXT 0x01
#define SWAPWINDOW_PREVIOUS 0x02

#define APPBAR_UPDATE_CURRENT_WORKSPACE 1
#define APPBAR_UPDATE_CURRENT_FOCUS_WINDOW 2

BOOL CALLBACK InitWorkSpaces_Callback(HWND, LPARAM);
BOOL CALLBACK MaximizeAllWindows(HWND, LPARAM);
BOOL CALLBACK MinimizeAllWindows(HWND, LPARAM);

HWND GetWindowByWorkspaceID(UINT, UINT);
HWND* GetWorkspaceByID(UINT);

BOOL IsValidWindow(HWND);
BOOL AddWindowToWorkspace(HWND, UINT);
BOOL MoveWindowToWorkspaceByID(HWND, UINT, UINT);
BOOL SwitchToWorkspace(UINT);
BOOL RemoveWindowFromWorkspace(HWND, UINT);

void SwitchToNextWorkspace();
void SwitchToPreviousWorkspace();
void TileWindowVertical();
void TileWindowHorizontal();
void HideWorkspaceByID(UINT);
void ShowWorkspaceByID(UINT);
void UpdateCurrentWorkspaceLayout();
void UpdateWorkspaceLayout(UINT);
void FocusWindow(UINT, UINT);
void FocusNextWindow();
void FocusPreviousWindow();
void RefreshWorkspace(UINT);
void UpdateTotalWindowInWorkspace(UINT);
void SwapCurrentFocusWindow(UINT, UINT);
void SendCurrentWorkspaceInfoThroughIPC(HWND);
void SendCurrentFocusWindowThroughIPC(HWND, HWND);
void ToggleWindow(HWND);
void UpdateFocusIndice(UINT, HWND);
